---
kind: Service
apiVersion: v1
metadata:
  name: stateful-rest-sample
  labels:
    app: stateful-rest-sample
  namespace: diploma-test
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: stateful-rest-sample

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-rest-sample
  labels:
    app: stateful-rest-sample
  namespace: diploma-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-rest-sample
  template:
    metadata:
      labels:
        app: stateful-rest-sample
    spec:
      containers:
      - name: stateful-rest-sample
        image: hostops/stateful-rest-sample:1.0.2-arm7
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: postgres://crate@crate-external-service.diploma-test.svc:5432/restsample
        ports:
        - containerPort: 8080
